### PR TITLE
Use TypeScript instead of Typescript

### PR DESCRIPTION
**Pull request by tnir**
https://www.typescriptlang.org/

### CODE REVIEW

**Comment by tnir** [comment]
Anyone can have a look??

**Comment by naohiro-t** [comment]
Apologies for the huge delay here and thank you for your contribution.

**Comment by tnir** [comment]
@naohiro-t Thanks for merging, but I still see "Typescript" at https://adele.uxpin.com/. What should we do? 😭

**Comment by naohiro-t** [comment]
@tnir I have not deployed to adele.uxpin.com yet, but also if we want to change the table header, we need to make sure we are using "TypeScript" in all companies (Well, as long as first item's(dropbox) label is TypeScript, it's enough...but we should be consistent.)

https://github.com/UXPin/adele/blob/0b23f3a8286c0f4a417136307a4dcee9c1ad6466/src/components/table/table.jsx#L96

**Pull request merged**
